---
title: "Creativity in the Age of Machines"
date: 2025-05-08
categories: [substack]
format: html
---

<p>On <em>60 Minutes</em>, Bill Whitaker asked <a href="https://www.linkedin.com/in/giacomo-massari-16997242/">Giacomo Massari</a> of <a href="https://litix.com/en/#">LITIX</a> (a company using robots to carve marble sculptures) what many are thinking:</p><blockquote><p><em>&#8220;If you have a robot doing 99% of the work, where&#8217;s the artistry?&#8221;</em></p></blockquote><p>Massari didn&#8217;t blink:</p><blockquote><p><em>&#8220;In the idea, how you program the machine. It&#8217;s a work of art because it&#8217;s an artistic approach. You need to have a sculptural background to program the machine in the way that you want.&#8221;</em></p></blockquote><p>Translation: the chisel is code. The artist is still here. She just speaks Python.</p><p>This is the new creative battleground. As AI and automation steamroll into traditionally &#8220;human&#8221; domains, we have two choices: evolve, or complain from the cheap seats. The future of creativity isn&#8217;t about resisting the machine. It&#8217;s about learning how to direct it.</p><p>We&#8217;re not being replaced by AI. We&#8217;re being replaced by people who know how to work with it.</p><div class="captioned-image-container"><figure><div class="youtube-wrap" id="youtube2-_VlkMuo2Zcs"><div class="youtube-inner"></div></div></figure></div><p>Whitaker, B. (2024) <em>Robots chisel out the future of sculpture as some artists embrace change and others push back</em>. 60 Minutes, CBS News. Available at: <a href="https://www.youtube.com/watch?v=_VlkMuo2Zcs">https://www.youtube.com/watch?v=_VlkMuo2Zcs</a> (Accessed: 4 April 2025).</p><p>#AI #Creativity #Design #Automation #GenerativeAI #FutureOfWork #ArtAndTechnology</p>
