project:
  type: website
  output-dir: _site
  resources:
    - assets/**
    - downloads/**

website:
  title: "Digital Acumen | Solar Investment Case"
  site-url: "https://marcelmare.com/dla-course-2/"
  search: false
  navbar: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    smooth-scroll: true
    code-copy: false
    anchor-sections: false
    link-external-newwindow: false
    include-after-body:
      - includes/course-state.html

execute:
  freeze: auto